/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CartGoodsHome: typeof import('./src/components/cart/CartGoodsHome.vue')['default']
    CartGoodsItem: typeof import('./src/components/cart/CartGoodsItem.vue')['default']
    ChitchatNavBar: typeof import('./src/components/chitchat/ChitchatNavBar.vue')['default']
    GoodsData: typeof import('./src/components/commonly/GoodsData.vue')['default']
    GoodsDetailTopNavBar: typeof import('./src/components/goods/GoodsDetailTopNavBar.vue')['default']
    HelloWorld: typeof import('./src/components/commonly/HelloWorld.vue')['default']
    HomeChoiceness: typeof import('./src/components/home/HomeChoiceness.vue')['default']
    HomeChoicenessItem: typeof import('./src/components/home/HomeChoicenessItem.vue')['default']
    HomeEverydayRecommend: typeof import('./src/components/home/HomeEverydayRecommend.vue')['default']
    HomeLikeItem: typeof import('./src/components/home/HomeLikeItem.vue')['default']
    HomeNewUser: typeof import('./src/components/home/HomeNewUser.vue')['default']
    HomeTop: typeof import('./src/components/home/HomeTop.vue')['default']
    HomeTopActivity: typeof import('./src/components/home/HomeTopActivity.vue')['default']
    HomeTopClassify: typeof import('./src/components/home/HomeTopClassify.vue')['default']
    HomeTopPledge: typeof import('./src/components/home/HomeTopPledge.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RightRoute: typeof import('./src/components/commonly/RightRoute.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScannedItem: typeof import('./src/components/commonly/ScannedItem.vue')['default']
    SearchBox: typeof import('./src/components/commonly/SearchBox.vue')['default']
    SearchTop: typeof import('./src/components/search/SearchTop.vue')['default']
    TheWelcome: typeof import('./src/components/commonly/TheWelcome.vue')['default']
    UserAccountInformation: typeof import('./src/components/user/UserAccountInformation.vue')['default']
    UserCommon: typeof import('./src/components/user/UserCommon.vue')['default']
    UserOrderForm: typeof import('./src/components/user/UserOrderForm.vue')['default']
    UserTop: typeof import('./src/components/user/UserTop.vue')['default']
    UserTopData: typeof import('./src/components/user/UserTopData.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanField: typeof import('vant/es')['Field']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    WelcomeItem: typeof import('./src/components/commonly/WelcomeItem.vue')['default']
  }
}
